In [6]:
import geopandas as gpd
from pathlib import Path

BASE_DIR = Path.cwd().parent
gdf = gpd.read_file(BASE_DIR / "data" / "clean" / "grid_250m_waste_bins.gpkg", layer="grid_bins")
gdf.head(), gdf.crs, gdf[["bins_total","bins_park_assets","bins_street_furniture"]].sum()

gdf.head()

,cell_id,bins_total,bins_park_assets,bins_street_furniture,geometry
0,0,0,0,0,"POLYGON ((607837.395 4824768.166, 607837.395 4..."
1,1,0,0,0,"POLYGON ((607837.395 4825018.166, 607837.395 4..."
2,2,0,0,0,"POLYGON ((607837.395 4825268.166, 607837.395 4..."
3,3,0,0,0,"POLYGON ((607837.395 4825518.166, 607837.395 4..."
4,4,0,0,0,"POLYGON ((607837.395 4825768.166, 607837.395 4..."

In [7]:
gdf[["cell_id", "bins_total", "bins_park_assets", "bins_street_furniture"]].head(10)

   cell_id  bins_total  bins_park_assets  bins_street_furniture
0        0           0                 0                      0
1        1           0                 0                      0
2        2           0                 0                      0
3        3           0                 0                      0
4        4           0                 0                      0
5        5           0                 0                      0
6        6           0                 0                      0
7        7           0                 0                      0
8        8           0                 0                      0
9        9           0                 0                      0

In [8]:
gdf["bins_total"].describe()

count    25024.000000
mean         0.608416
std          1.726538
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         30.000000
Name: bins_total, dtype: float64